INSERT INTO Z02.EMPLOYEES (EMPLOYEE_ID, NAME, SURNAME, SALARY, POSITION_ID, SERVICE_PLACE_ID, LOGIN_DATA_ID, NODE_ID) VALUES (22, 'courier', 'courier', null, 21, null, 22, 2);
INSERT INTO Z02.EMPLOYEES (EMPLOYEE_ID, NAME, SURNAME, SALARY, POSITION_ID, SERVICE_PLACE_ID, LOGIN_DATA_ID, NODE_ID) VALUES (43, 'admin', 'admin', 6000.00, 22, 1, 4, 1);
